spring.application.name=skill-swap

# Hibernate & DB
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Fix for H2 console with Spring Security:
spring.h2.console.settings.web-allow-others=true

# Datasource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT Configuration
app.jwt.secret=dev-secret-key-must-be-very-long-and-secure-12345
app.jwt.expiration=86400000